name: RandomItemDropsPlugin
version: '${project.version}'
main: org.seymourg_og.randomitemdropsplugin.RandomItemDropsPlugin
api-version: '1.20'
commands:
  rid:
    description: restart plugin
    usage: /<command>